source 'https://rubygems.org'

# Specify your gem's dependencies in mapa76-core.gemspec
gemspec

gem "rake"
gem "capistrano"
gem "yajl-ruby", :require => "yajl/json_gem"

group :extra do
  gem "turn"
  gem "guard"
  gem "guard-minitest"
  gem "rb-inotify", :require => false
  gem "rb-fsevent", :require => false
  gem "rb-fchange", :require => false
end
