source 'https://rubygems.org'

gem "mapa76-core", path: "../chaos"

gem "activesupport", :require => false
gem 'dotenv'
gem "amatch"
gem "bson_ext"
gem "docsplit"
gem "hashie", :require => false
gem "httpi"
gem "log4r"
gem "mongoid"
gem "mongoid-pagination"
gem "multi_json"
gem "nokogiri"
gem "oj"
gem "rake"
gem "tire"
gem "pry", :require => false
gem "json", "~> 1.7.7"
gem "httparty"
gem "ruby-progressbar", require: false

group :development do
  #gem "pry-debugger"

  gem "capistrano"
  gem "capistrano-ext"
end

group :test do
  gem "database_cleaner"
  gem "factory_girl"
  gem "minitest"#, require: "minitest/autorun"
  gem "mocha", require: false
end
