source 'https://rubygems.org'

gem "mapa76-core", path: "../chaos"

gem "activesupport", :require => false
gem "amatch"
gem "bson_ext"
gem "docsplit"
gem "hashie", :require => false
gem "freeling-analyzer"
gem "geokit"
gem "httpi"
gem "log4r"
gem "mongoid"
gem "mongoid-pagination"
gem "multi_json"
gem "nokogiri"
gem "oj"
gem "rake"
gem "pry", :require => false
gem "json", "~> 1.7.7"

group :development do
  #gem "pry-debugger"

  gem "capistrano"
  gem "capistrano-ext"
  gem "rvm-capistrano"
end

group :test do
  gem "database_cleaner"
  gem "factory_girl"
  gem "guard"
  gem "guard-minitest"
  gem "minitest", "~> 2.6.0", :require => "minitest/autorun"
  gem "minitest-spec-context"
  gem "mocha", require: false
  gem "shoulda-context"
  gem "turn"
end
