setup:
	mkdir /home/deploy/apps/mapa76.info/hephaestus/shared/config
	cp /home/deploy/apps/mapa76.info/hephaestus/current/config/elasticsearch.yml.sample /home/deploy/apps/mapa76.info/hephaestus/shared/config/elasticsearch.yml
	cp /home/deploy/apps/mapa76.info/hephaestus/current/config/mongoid.yml.sample /home/deploy/apps/mapa76.info/hephaestus/shared/config/mongoid.yml
	cp /home/deploy/apps/mapa76.info/hephaestus/current/config/monit.yml.sample /home/deploy/apps/mapa76.info/hephaestus/shared/config/monit.yml
	cp /home/deploy/apps/mapa76.info/hephaestus/current/config/resque.yml.sample /home/deploy/apps/mapa76.info/hephaestus/shared/config/resque.yml
	cp /home/deploy/apps/mapa76.info/hephaestus/current/config/workers.yml.sample /home/deploy/apps/mapa76.info/hephaestus/shared/config/workers.yml
	touch /home/deploy/apps/mapa76.info/hephaestus/shared/.env
	cp /home/deploy/apps/mapa76.info/hephaestus/current/config/freeling.sh /home/deploy/apps/mapa76.info/hephaestus/shared/config/
	sudo ln -s /home/deploy/apps/mapa76.info/hephaestus/shared/config/freeling.sh /etc/init.d/freeling

