source 'https://rubygems.org'

gem 'rails', '~>3.2.8'
gem 'mapa76-core', path: '../chaos'

group :assets do
  gem 'backbone-on-rails'
  gem 'jquery-ui-rails'
  gem 'sass-rails',   '~> 3.2.3'
  gem 'compass-rails'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'therubyracer'
  gem 'uglifier', '>= 1.0.3'
  gem 'bootstrap-sass'
  gem 'bootswatch-rails'
end

group :development do
  gem "better_errors"
  gem 'binding_of_caller'
  gem 'capistrano'
  gem 'capistrano-unicorn', :require => false
  gem 'debugger'
  gem 'rvm-capistrano'
  gem 'ruby-prof'
end

group :development, :test do
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'minitest-rails'
  gem 'minitest-spec-context'
  gem 'minitest-colorize'
  gem 'minitest-focus'
  gem 'mocha', require: false
  gem 'spring'
end

gem 'devise'
gem 'haml'
gem 'sass'
gem 'haml-rails'
gem 'mongoid'
gem 'mongoid-pagination'
gem 'oj'
gem 'simple_form'
gem 'rabl'
gem 'rails_admin'
gem 'unicorn'
gem 'will_paginate-bootstrap', :require => "will_paginate-bootstrap"
gem 'whenever', require: false

