source 'https://rubygems.org'

gem 'rails', '~>3.2.8'
gem 'mapa76-core', path: '../chaos/' #github: 'hhba/mapa76-core'

group :assets do
  gem 'backbone-on-rails'
  gem 'jquery-ui-rails'
  gem 'sass-rails',   '~> 3.2.3'
  gem 'compass-rails'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'therubyracer'
  gem 'uglifier', '>= 1.0.3'
  gem 'bootstrap-sass'
  gem 'bootswatch-rails'
end

group :development, :test do
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'guard-test'
  gem 'ruby-prof'
  gem 'shoulda-context'
  gem 'shoulda-matchers'
end

group :development do
  gem 'capistrano'
  gem 'capistrano-unicorn', :require => false
  gem 'rvm-capistrano'

  gem "better_errors"
  gem 'debugger'
end

gem 'devise'
gem 'haml'
gem 'sass'
gem 'haml-rails'
gem 'jquery-rails', '2.1.4'
gem 'mongoid'
gem 'mongoid-pagination'
gem 'oj'
gem 'simple_form'
gem 'rabl'
gem 'unicorn'
gem 'will_paginate-bootstrap', :require => "will_paginate-bootstrap"
