source 'https://rubygems.org'

gem 'rails', '~>3.2.8'
gem 'mapa76-core', path: '../chaos'

group :development do
  gem "better_errors"
  gem 'binding_of_caller'
  gem 'capistrano'
  gem 'capistrano-unicorn', require: false
  gem 'ruby-prof'
end

group :development, :test do
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'minitest-rails'
  gem 'minitest-spec-context'
  gem 'minitest-colorize'
  gem 'minitest-focus'
  gem 'mocha', require: false
  gem 'spring'
end

gem 'devise'
gem 'elasticsearch'
gem 'haml'
gem 'figaro'
gem 'sass'
gem 'haml-rails'
gem 'mongoid'
gem 'mongoid-pagination'
gem 'oj'
gem 'simple_form'
gem 'rabl'
gem 'rails_admin'
gem 'unicorn'
gem 'resque-web', require: 'resque_web'
gem 'will_paginate-bootstrap', :require => "will_paginate-bootstrap"
gem 'whenever', require: false
